name: Deploy to Production (Main)

on:
  push:
    branches:
      - main  # Trigger hanya berjalan saat push ke branch main

jobs:
  web-deploy:
    name: Deploy Main to Production
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files to InfinityFree Main
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ${{ secrets.FTP_SERVER_MAIN }}
        username: ${{ secrets.FTP_USERNAME_MAIN }}
        password: ${{ secrets.FTP_PASSWORD_MAIN }}
        server-dir: htdocs/  # Sesuaikan dengan folder root domain utama Anda
